import org.codehaus.groovy.runtime.GStringImpl

plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '3.3.4'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

ext {
    springBootVersion = '3.3.4'
    lombokVersion = '1.18.34'
    jacksonVersion = '2.15.3'
}

dependencies {
    //implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-configuration-processor:$springBootVersion"
    // Validation
    implementation "org.springframework.boot:spring-boot-starter:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-validation:$springBootVersion"
    // Spring Boot Actuator: HealthCheck, Metrics
    implementation "org.springframework.boot:spring-boot-starter-actuator:${springBootVersion}"
    // Lombok
    implementation "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    // Kafka
    implementation "org.springframework.kafka:spring-kafka:${springBootVersion}"
    // Jackson
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    // Spring Boot starter for JDBC (no JPA, no ORM)
    implementation "org.springframework.boot:spring-boot-starter-jdbc:${springBootVersion}"
    // PostgreSQL JDBC driver
    runtimeOnly 'org.postgresql:postgresql:42.7.5'
}